global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'ttssmonitor'
    scrape_interval: 5m
    static_configs:
    - targets: ['10.88.0.10:8080']
    